# Generated by Django 5.0.3 on 2024-03-21 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_customuser_balance_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
